// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v4.25.3
// source: Serve2.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FastArgs2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Give  int32 `protobuf:"varint,1,opt,name=give,proto3" json:"give,omitempty"`
	Times int64 `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
}

func (x *FastArgs2) Reset() {
	*x = FastArgs2{}
	mi := &file_Serve2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FastArgs2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastArgs2) ProtoMessage() {}

func (x *FastArgs2) ProtoReflect() protoreflect.Message {
	mi := &file_Serve2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastArgs2.ProtoReflect.Descriptor instead.
func (*FastArgs2) Descriptor() ([]byte, []int) {
	return file_Serve2_proto_rawDescGZIP(), []int{0}
}

func (x *FastArgs2) GetGive() int32 {
	if x != nil {
		return x.Give
	}
	return 0
}

func (x *FastArgs2) GetTimes() int64 {
	if x != nil {
		return x.Times
	}
	return 0
}

type FastReply2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsGet int32 `protobuf:"varint,1,opt,name=isGet,proto3" json:"isGet,omitempty"`
}

func (x *FastReply2) Reset() {
	*x = FastReply2{}
	mi := &file_Serve2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FastReply2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastReply2) ProtoMessage() {}

func (x *FastReply2) ProtoReflect() protoreflect.Message {
	mi := &file_Serve2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastReply2.ProtoReflect.Descriptor instead.
func (*FastReply2) Descriptor() ([]byte, []int) {
	return file_Serve2_proto_rawDescGZIP(), []int{1}
}

func (x *FastReply2) GetIsGet() int32 {
	if x != nil {
		return x.IsGet
	}
	return 0
}

var File_Serve2_proto protoreflect.FileDescriptor

var file_Serve2_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35,
	0x0a, 0x09, 0x46, 0x61, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x69, 0x76, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x22, 0x0a, 0x0a, 0x46, 0x61, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x47, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x47, 0x65, 0x74, 0x32, 0x5d, 0x0a, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x32, 0x12, 0x2b, 0x0a, 0x10, 0x46, 0x61, 0x73, 0x74, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x0a, 0x2e, 0x46, 0x61, 0x73, 0x74, 0x41,
	0x72, 0x67, 0x73, 0x32, 0x1a, 0x0b, 0x2e, 0x46, 0x61, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0x12, 0x25, 0x0a, 0x0a, 0x54, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x0a, 0x2e, 0x46, 0x61, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x32, 0x1a, 0x0b, 0x2e, 0x46, 0x61,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Serve2_proto_rawDescOnce sync.Once
	file_Serve2_proto_rawDescData = file_Serve2_proto_rawDesc
)

func file_Serve2_proto_rawDescGZIP() []byte {
	file_Serve2_proto_rawDescOnce.Do(func() {
		file_Serve2_proto_rawDescData = protoimpl.X.CompressGZIP(file_Serve2_proto_rawDescData)
	})
	return file_Serve2_proto_rawDescData
}

var file_Serve2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Serve2_proto_goTypes = []any{
	(*FastArgs2)(nil),  // 0: FastArgs2
	(*FastReply2)(nil), // 1: FastReply2
}
var file_Serve2_proto_depIdxs = []int32{
	0, // 0: Server2.FastReturnServer:input_type -> FastArgs2
	0, // 1: Server2.TellServer:input_type -> FastArgs2
	1, // 2: Server2.FastReturnServer:output_type -> FastReply2
	1, // 3: Server2.TellServer:output_type -> FastReply2
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Serve2_proto_init() }
func file_Serve2_proto_init() {
	if File_Serve2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Serve2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Serve2_proto_goTypes,
		DependencyIndexes: file_Serve2_proto_depIdxs,
		MessageInfos:      file_Serve2_proto_msgTypes,
	}.Build()
	File_Serve2_proto = out.File
	file_Serve2_proto_rawDesc = nil
	file_Serve2_proto_goTypes = nil
	file_Serve2_proto_depIdxs = nil
}
